defaults: &defaults
  app_name: Locomotive
  google_analytics:
    enabled: false

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  google_analytics:
    enabled: true
    tracking_id: 'UA-655293-8'

production:
  <<: *defaults
