defaults: &defaults
  app_name: Locomotive
  google_analytics:
    enabled: false
  http_auth:
    login: 'locomotive'
    password: 'password'
  exception_notification:
    sender_address: 'error@locomotive.com'
    exception_recipients: 'lukasz@llp.pl'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  google_analytics:
    enabled: true
    tracking_id: 'UA-655293-8'

production:
  <<: *defaults
